### ISSUE TITLE
python3下的几处修改

### ISSUE THREAD

**Issue by ybNero** [bojone/ee-2019-baseline#1]
line 52/line 92：`range(len())`改成`list(range(len()))`
line 265：`print`加括号

**Comment by liawa** [comment]
这些错误已改，是改成python3.6版的，但在自定义loss时总会报错，TypeError: compile() missing 1 required positional argument: 'loss'。
然后，我改成
def myloss(s1_in, ps1):
   loss1 = K.mean(K.categorical_crossentropy(s1_in, ps1, from_logits=True))
   loss2 = K.mean(K.categorical_crossentropy(s2_in, ps2, from_logits=True))
   loss = loss1 + loss2
   return loss
train_model.compile(optimizer=Adam(1e-3),loss=myloss)
跑到代码fit_generator最后报错AttributeError: 'NoneType' object has no attribute 'shape'。

**Comment by liawa** [comment]
keras版本原因，升到2.2.4就好了，我之前的修改是错的
